version: '2'
services:
  app:
    build: ./app
    command: python app.py
    expose:
      - "5000"
    volumes:
      - /tmp:/tmp

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    extra_hosts:
      - "process-xml:127.0.0.1"

  redis:
    image: redis
    expose:
      - "6379"

  worker:
    build: ./worker
    working_dir: /app
    command: celery -A tasks worker
    environment:
      C_FORCE_ROOT: 'true'
    volumes:
      - ./app:/app
      - /tmp:/tmp